SNR_dB = -10:8;
BER_Numerically = ComputeBER_Numerically_2(SNR_dB);      
BER_Analytically = ComputeBER_Analytically_2(SNR_dB);
figure;
semilogy(SNR_dB, BER_Numerically);
grid on;
title('Req. B');
xlabel('SNR in dB');
ylabel('BER');
hold on;
semilogy(SNR_dB, BER_Analytically,'--');
legend('Numerically', 'Analytically');